name: Build Laravel Test API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
    - uses: actions/checkout@v3

    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push image
      run: docker push $IMAGE_NAME:latest
      